---
base:
  build: .
  volumes:
    - ".:/app"
  ports:
    - "3000:3000"

rake:
  extends:
    file: docker-compose.yml
    service: base
  environment:
    QINIU_BUCKET: shandianying
    QINIU_ACCESS_KEY: T7GaBoACrRQwRW3xUHC-kg5BhdP3t8fKfnstDTJn
    QINIU_SECRET_KEY: a0Eh8lcTqW5adr0NbIMhnBzWWIuJfIWbR1k6Ov8w
  entrypoint: ./bin/rake
